import {Package} from './package';

export const PACKAGE_OPTIONS: Package[] = [
  new Package(0,
    1,
    2,
    15,
    26,
    1,
    'GSS-DLE SATCHEL',
    'DLE SATCHEL',
    'DLE',
    'Box',
    'Usually fits 1 item of clothing',
    4.95),
  new Package(0,
    1,
    2,
    21,
    26,
    2,
    'GSS-A5 SATCHEL',
    'A5 SATCHEL',
    'AS',
    'Box',
    'Usually fits 1 item of clothing',
    6.95),
  new Package(0,
    1,
    2,
    28,
    39,
    2,
    'GSS-A4 SATCHEL',
    'A4 SATCHEL',
    'A4',
    'Box',
    'Usually fits 2 items of clothing',
    8.95),
  new Package(0,
    1,
    4,
    36,
    41,
    2,
    'GSS-A3 SATCHEL',
    'A3 SATCHEL',
    'A3',
    'Box',
    'Usually fits 3 items of clothing',
    9.95),
  new Package(0,
    1,
    5,
    45,
    45,
    2,
    'GSS-A2 SATCHEL',
    'A2 SATCHEL',
    'A2',
    'Box',
    'Usually fits 4 items of clothing',
    11.95)
];
