import {Injectable} from '@angular/core';
import {CountryWithCodeModel} from '../models/country-with-code.model';

@Injectable()
export class CountriesListProviderService {
  private _fullCountriesList: CountryWithCodeModel[] = [
    new CountryWithCodeModel('NZ', 'NEW ZEALAND'),
    new CountryWithCodeModel('AU', 'AUSTRALIA'),
    new CountryWithCodeModel('US', 'UNITED STATES'),
    new CountryWithCodeModel('GB', 'GREAT BRITAIN'),
    new CountryWithCodeModel('UK', 'UNITED KINGDOM'),
    new CountryWithCodeModel('CN', 'CHINA'),
    new CountryWithCodeModel('AF', 'AFGHANISTAN'),
    new CountryWithCodeModel('AX', 'ÅLAND ISLANDS'),
    new CountryWithCodeModel('AL', 'ALBANIA'),
    new CountryWithCodeModel('AY', 'ALDERNEY'),
    new CountryWithCodeModel('DZ', 'ALGERIA'),
    new CountryWithCodeModel('AS', 'AMERICAN SAMOA'),
    new CountryWithCodeModel('AD', 'ANDORRA'),
    new CountryWithCodeModel('AO', 'ANGOLA'),
    new CountryWithCodeModel('AI', 'ANGUILLA'),
    new CountryWithCodeModel('AQ', 'ANTARCTICA'),
    new CountryWithCodeModel('AG', 'ANTIGUA AND BARBUDA'),
    new CountryWithCodeModel('AR', 'ARGENTINA'),
    new CountryWithCodeModel('AM', 'ARMENIA'),
    new CountryWithCodeModel('AW', 'ARUBA'),
    new CountryWithCodeModel('AT', 'AUSTRIA'),
    new CountryWithCodeModel('AZ', 'AZERBAIJAN'),
    new CountryWithCodeModel('AC', 'AZORES'),
    new CountryWithCodeModel('BS', 'BAHAMAS'),
    new CountryWithCodeModel('BH', 'BAHRAIN'),
    new CountryWithCodeModel('BD', 'BANGLADESH'),
    new CountryWithCodeModel('BB', 'BARBADOS'),
    new CountryWithCodeModel('BY', 'BELARUS'),
    new CountryWithCodeModel('BE', 'BELGIUM'),
    new CountryWithCodeModel('BZ', 'BELIZE'),
    new CountryWithCodeModel('BJ', 'BENIN'),
    new CountryWithCodeModel('BM', 'BERMUDA'),
    new CountryWithCodeModel('BT', 'BHUTAN'),
    new CountryWithCodeModel('BO', 'BOLIVIA'),
    new CountryWithCodeModel('BA', 'BOSNIA AND HERZEGOVINA'),
    new CountryWithCodeModel('BW', 'BOTSWANA'),
    new CountryWithCodeModel('BV', 'BOUVET ISLAND'),
    new CountryWithCodeModel('BR', 'BRAZIL'),
    new CountryWithCodeModel('IO', 'BRITISH INDIAN OCEAN TERRITORY'),
    new CountryWithCodeModel('BN', 'BRUNEI DARUSSALAM'),
    new CountryWithCodeModel('BG', 'BULGARIA'),
    new CountryWithCodeModel('BF', 'BURKINA FASO'),
    new CountryWithCodeModel('BI', 'BURUNDI'),
    new CountryWithCodeModel('KH', 'CAMBODIA'),
    new CountryWithCodeModel('CM', 'CAMEROON'),
    new CountryWithCodeModel('CA', 'CANADA'),
    new CountryWithCodeModel('IC', 'CANARY ISLANDS'),
    new CountryWithCodeModel('CV', 'CAPE VERDE'),
    new CountryWithCodeModel('KY', 'CAYMAN ISLANDS'),
    new CountryWithCodeModel('CF', 'CENTRAL AFRICAN REPUBLIC'),
    new CountryWithCodeModel('TD', 'CHAD'),
    new CountryWithCodeModel('CL', 'CHILE'),
    new CountryWithCodeModel('CX', 'CHRISTMAS ISLAND'),
    new CountryWithCodeModel('CC', 'COCOS (KEELING) ISLANDS'),
    new CountryWithCodeModel('CO', 'COLOMBIA'),
    new CountryWithCodeModel('KM', 'COMOROS'),
    new CountryWithCodeModel('CG', 'CONGO'),
    new CountryWithCodeModel('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'),
    new CountryWithCodeModel('CK', 'COOK ISLANDS'),
    new CountryWithCodeModel('CR', 'COSTA RICA'),
    new CountryWithCodeModel('CI', 'CÔTE D\'IVOIRE'),
    new CountryWithCodeModel('HR', 'CROATIA'),
    new CountryWithCodeModel('CU', 'CUBA'),
    new CountryWithCodeModel('CY', 'CYPRUS'),
    new CountryWithCodeModel('CZ', 'CZECH REPUBLIC'),
    new CountryWithCodeModel('DK', 'DENMARK'),
    new CountryWithCodeModel('DJ', 'DJIBOUTI'),
    new CountryWithCodeModel('DM', 'DOMINICA'),
    new CountryWithCodeModel('DO', 'DOMINICAN REPUBLIC'),
    new CountryWithCodeModel('TP', 'EAST TIMOR'),
    new CountryWithCodeModel('EC', 'ECUADOR'),
    new CountryWithCodeModel('EG', 'EGYPT'),
    new CountryWithCodeModel('SV', 'EL SALVADOR'),
    new CountryWithCodeModel('GQ', 'EQUATORIAL GUINEA'),
    new CountryWithCodeModel('ER', 'ERITREA'),
    new CountryWithCodeModel('EE', 'ESTONIA'),
    new CountryWithCodeModel('ET', 'ETHIOPIA'),
    new CountryWithCodeModel('FK', 'FALKLAND ISLANDS (MALVINAS)'),
    new CountryWithCodeModel('FO', 'FAROE ISLANDS'),
    new CountryWithCodeModel('FJ', 'FIJI'),
    new CountryWithCodeModel('FI', 'FINLAND'),
    new CountryWithCodeModel('FR', 'FRANCE'),
    new CountryWithCodeModel('GF', 'FRENCH GUIANA'),
    new CountryWithCodeModel('PF', 'FRENCH POLYNESIA'),
    new CountryWithCodeModel('TF', 'FRENCH SOUTHERN TERRITORIES'),
    new CountryWithCodeModel('GA', 'GABON'),
    new CountryWithCodeModel('GM', 'GAMBIA'),
    new CountryWithCodeModel('GE', 'GEORGIA'),
    new CountryWithCodeModel('DE', 'GERMANY'),
    new CountryWithCodeModel('GH', 'GHANA'),
    new CountryWithCodeModel('GI', 'GIBRALTAR'),
    new CountryWithCodeModel('GR', 'GREECE'),
    new CountryWithCodeModel('GL', 'GREENLAND'),
    new CountryWithCodeModel('GD', 'GRENADA'),
    new CountryWithCodeModel('GP', 'GUADELOUPE'),
    new CountryWithCodeModel('GU', 'GUAM'),
    new CountryWithCodeModel('GT', 'GUATEMALA'),
    new CountryWithCodeModel('GG', 'GUERNSEY'),
    new CountryWithCodeModel('GN', 'GUINEA'),
    new CountryWithCodeModel('GW', 'GUINEA-BISSAU'),
    new CountryWithCodeModel('GY', 'GUYANA'),
    new CountryWithCodeModel('HT', 'HAITI'),
    new CountryWithCodeModel('HM', 'HEARD ISLAND AND MCDONALD ISLANDS'),
    new CountryWithCodeModel('VA', 'HOLY SEE (VATICAN CITY STATE)'),
    new CountryWithCodeModel('HN', 'HONDURAS'),
    new CountryWithCodeModel('HK', 'HONG KONG'),
    new CountryWithCodeModel('HU', 'HUNGARY'),
    new CountryWithCodeModel('IS', 'ICELAND'),
    new CountryWithCodeModel('IN', 'INDIA'),
    new CountryWithCodeModel('ID', 'INDONESIA'),
    new CountryWithCodeModel('IR', 'IRAN, ISLAMIC REPUBLIC OF'),
    new CountryWithCodeModel('IQ', 'IRAQ'),
    new CountryWithCodeModel('IE', 'IRELAND'),
    new CountryWithCodeModel('IM', 'ISLE OF MAN'),
    new CountryWithCodeModel('IL', 'ISRAEL'),
    new CountryWithCodeModel('IT', 'ITALY'),
    new CountryWithCodeModel('JM', 'JAMAICA'),
    new CountryWithCodeModel('JP', 'JAPAN'),
    new CountryWithCodeModel('JE', 'JERSEY'),
    new CountryWithCodeModel('JO', 'JORDAN'),
    new CountryWithCodeModel('KZ', 'KAZAKHSTAN'),
    new CountryWithCodeModel('KE', 'KENYA'),
    new CountryWithCodeModel('KI', 'KIRIBATI'),
    new CountryWithCodeModel('KW', 'KUWAIT'),
    new CountryWithCodeModel('KG', 'KYRGYZSTAN'),
    new CountryWithCodeModel('LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC'),
    new CountryWithCodeModel('LV', 'LATVIA'),
    new CountryWithCodeModel('LB', 'LEBANON'),
    new CountryWithCodeModel('LS', 'LESOTHO'),
    new CountryWithCodeModel('LR', 'LIBERIA'),
    new CountryWithCodeModel('LY', 'LIBYAN ARAB JAMAHIRIYA'),
    new CountryWithCodeModel('LI', 'LIECHTENSTEIN'),
    new CountryWithCodeModel('LT', 'LITHUANIA'),
    new CountryWithCodeModel('LU', 'LUXEMBOURG'),
    new CountryWithCodeModel('MO', 'MACAO'),
    new CountryWithCodeModel('MK', 'MACEDONIA'),
    new CountryWithCodeModel('MG', 'MADAGASCAR'),
    new CountryWithCodeModel('MW', 'MALAWI'),
    new CountryWithCodeModel('MY', 'MALAYSIA'),
    new CountryWithCodeModel('MV', 'MALDIVES'),
    new CountryWithCodeModel('ML', 'MALI'),
    new CountryWithCodeModel('MT', 'MALTA'),
    new CountryWithCodeModel('MH', 'MARSHALL ISLANDS'),
    new CountryWithCodeModel('MQ', 'MARTINIQUE'),
    new CountryWithCodeModel('MR', 'MAURITANIA'),
    new CountryWithCodeModel('MU', 'MAURITIUS'),
    new CountryWithCodeModel('YT', 'MAYOTTE'),
    new CountryWithCodeModel('MX', 'MEXICO'),
    new CountryWithCodeModel('FM', 'MICRONESIA, FEDERATED STATES OF'),
    new CountryWithCodeModel('MI', 'MIDWAY ISLAND'),
    new CountryWithCodeModel('MD', 'MOLDOVA, REPUBLIC OF'),
    new CountryWithCodeModel('MC', 'MONACO'),
    new CountryWithCodeModel('MN', 'MONGOLIA'),
    new CountryWithCodeModel('ME', 'MONTENEGRO'),
    new CountryWithCodeModel('MS', 'MONTSERRAT'),
    new CountryWithCodeModel('MA', 'MOROCCO'),
    new CountryWithCodeModel('MZ', 'MOZAMBIQUE'),
    new CountryWithCodeModel('MM', 'MYANMAR'),
    new CountryWithCodeModel('NA', 'NAMIBIA'),
    new CountryWithCodeModel('NR', 'NAURU'),
    new CountryWithCodeModel('NP', 'NEPAL'),
    new CountryWithCodeModel('NL', 'NETHERLANDS'),
    new CountryWithCodeModel('AN', 'NETHERLANDS ANTILLES'),
    new CountryWithCodeModel('NC', 'NEW CALEDONIA'),
    new CountryWithCodeModel('NI', 'NICARAGUA'),
    new CountryWithCodeModel('NE', 'NIGER'),
    new CountryWithCodeModel('NG', 'NIGERIA'),
    new CountryWithCodeModel('NU', 'NIUE'),
    new CountryWithCodeModel('NF', 'NORFOLK ISLAND'),
    new CountryWithCodeModel('KP', 'North Korea'),
    new CountryWithCodeModel('MP', 'NORTHERN MARIANA ISLANDS'),
    new CountryWithCodeModel('NO', 'NORWAY'),
    new CountryWithCodeModel('OM', 'OMAN'),
    new CountryWithCodeModel('PK', 'PAKISTAN'),
    new CountryWithCodeModel('PW', 'PALAU'),
    new CountryWithCodeModel('PS', 'PALESTINIAN TERRITORY, OCCUPIED'),
    new CountryWithCodeModel('PA', 'PANAMA'),
    new CountryWithCodeModel('PG', 'PAPUA NEW GUINEA'),
    new CountryWithCodeModel('PY', 'PARAGUAY'),
    new CountryWithCodeModel('PE', 'PERU'),
    new CountryWithCodeModel('PH', 'PHILIPPINES'),
    new CountryWithCodeModel('PN', 'PITCAIRN'),
    new CountryWithCodeModel('PL', 'POLAND'),
    new CountryWithCodeModel('PT', 'PORTUGAL'),
    new CountryWithCodeModel('PR', 'PUERTO RICO'),
    new CountryWithCodeModel('QA', 'QATAR'),
    new CountryWithCodeModel('RE', 'RÉUNION'),
    new CountryWithCodeModel('RO', 'ROMANIA'),
    new CountryWithCodeModel('RU', 'RUSSIAN FEDERATION'),
    new CountryWithCodeModel('RW', 'RWANDA'),
    new CountryWithCodeModel('BL', 'SAINT BARTHÉLEMY'),
    new CountryWithCodeModel('SH', 'SAINT HELENA'),
    new CountryWithCodeModel('KN', 'SAINT KITTS AND NEVIS'),
    new CountryWithCodeModel('LC', 'SAINT LUCIA'),
    new CountryWithCodeModel('MF', 'SAINT MARTIN'),
    new CountryWithCodeModel('PM', 'SAINT PIERRE AND MIQUELON'),
    new CountryWithCodeModel('VC', 'SAINT VINCENT AND THE GRENADINES'),
    new CountryWithCodeModel('WS', 'SAMOA'),
    new CountryWithCodeModel('SM', 'SAN MARINO'),
    new CountryWithCodeModel('ST', 'SAO TOME AND PRINCIPE'),
    new CountryWithCodeModel('SA', 'SAUDI ARABIA'),
    new CountryWithCodeModel('SN', 'SENEGAL'),
    new CountryWithCodeModel('RS', 'SERBIA'),
    new CountryWithCodeModel('SC', 'SEYCHELLES'),
    new CountryWithCodeModel('SL', 'SIERRA LEONE'),
    new CountryWithCodeModel('SG', 'SINGAPORE'),
    new CountryWithCodeModel('SK', 'SLOVAKIA'),
    new CountryWithCodeModel('SI', 'SLOVENIA'),
    new CountryWithCodeModel('SB', 'SOLOMON ISLANDS'),
    new CountryWithCodeModel('SO', 'SOMALIA'),
    new CountryWithCodeModel('ZA', 'SOUTH AFRICA'),
    new CountryWithCodeModel('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'),
    new CountryWithCodeModel('KR', 'South Korea'),
    new CountryWithCodeModel('SS', 'SOUTH SUDAN'),
    new CountryWithCodeModel('ES', 'SPAIN'),
    new CountryWithCodeModel('LK', 'SRI LANKA'),
    new CountryWithCodeModel('XE', 'ST EUSTATIUS'),
    new CountryWithCodeModel('SD', 'SUDAN'),
    new CountryWithCodeModel('SR', 'SURINAME'),
    new CountryWithCodeModel('SJ', 'SVALBARD AND JAN MAYEN'),
    new CountryWithCodeModel('SZ', 'SWAZILAND'),
    new CountryWithCodeModel('SE', 'SWEDEN'),
    new CountryWithCodeModel('CH', 'SWITZERLAND'),
    new CountryWithCodeModel('SY', 'SYRIAN ARAB REPUBLIC'),
    new CountryWithCodeModel('TW', 'TAIWAN, PROVINCE OF CHINA'),
    new CountryWithCodeModel('TJ', 'TAJIKISTAN'),
    new CountryWithCodeModel('TZ', 'TANZANIA, UNITED REPUBLIC OF'),
    new CountryWithCodeModel('TH', 'THAILAND'),
    new CountryWithCodeModel('TL', 'TIMOR-LESTE'),
    new CountryWithCodeModel('TG', 'TOGO'),
    new CountryWithCodeModel('TK', 'TOKELAU'),
    new CountryWithCodeModel('TO', 'TONGA'),
    new CountryWithCodeModel('TT', 'TRINIDAD AND TOBAGO'),
    new CountryWithCodeModel('TN', 'TUNISIA'),
    new CountryWithCodeModel('TR', 'TURKEY'),
    new CountryWithCodeModel('TM', 'TURKMENISTAN'),
    new CountryWithCodeModel('TC', 'TURKS AND CAICOS ISLANDS'),
    new CountryWithCodeModel('TV', 'TUVALU'),
    new CountryWithCodeModel('UG', 'UGANDA'),
    new CountryWithCodeModel('UA', 'UKRAINE'),
    new CountryWithCodeModel('AE', 'UNITED ARAB EMIRATES'),
    new CountryWithCodeModel('UM', 'UNITED STATES MINOR OUTLYING ISLANDS'),
    new CountryWithCodeModel('UY', 'URUGUAY'),
    new CountryWithCodeModel('UZ', 'UZBEKISTAN'),
    new CountryWithCodeModel('VU', 'VANUATU'),
    new CountryWithCodeModel('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF'),
    new CountryWithCodeModel('VN', 'VIETNAM'),
    new CountryWithCodeModel('VG', 'VIRGIN ISLANDS, BRITISH'),
    new CountryWithCodeModel('VI', 'VIRGIN ISLANDS, U.S.'),
    new CountryWithCodeModel('WK', 'WAKE ISLAND'),
    new CountryWithCodeModel('WF', 'WALLIS AND FUTUNA'),
    new CountryWithCodeModel('EH', 'WESTERN SAHARA'),
    new CountryWithCodeModel('YE', 'YEMEN'),
    new CountryWithCodeModel('ZM', 'ZAMBIA'),
    new CountryWithCodeModel('ZW', 'ZIMBABWE'),
  ];

  get FullCountriesList() {
    return this._fullCountriesList;
  }
}
